### ISSUE TITLE
WER score bigger than 1.0

### ISSUE THREAD

**Issue by matiasbattocchia** [jitsi/jiwer#41]
Literature states that WER is bounded between 0 and 1.

```python
wer(truth='fries', hypothesis='no fry')
```
gives

    > 2.0

Is this an expected behaviour?

**Comment by nikvaessen** [comment]
Yes.

Given the formula `WER = (S + D + I) / N)`, and your example with `N=1`, `D=1`, `S=1` would result in `WER = (1 + 1 + 0) / 1 = 2/1 = 2`.

See also https://en.wikipedia.org/wiki/Word_error_rate, which states:

_"Note that since N is the number of words in the reference, the word error rate can be larger than 1.0, and thus, the word accuracy can be smaller than 0.0. "_

Any literature which states WER is bonded between 0 and 1 is wrong (or has different assumptions perhaps).

**Comment by matiasbattocchia** [comment]
Very clear. Thanks for your response.
